version: '3.8'

services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}

    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: --bind-address=0.0.0.0

  backend:
    build: ./backend
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./backend:/code
    depends_on:
      - db
    environment:
      # Ensure these environment variables are defined in your .env file
      MARIADB_HOST: db
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}

      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_PROJECT_ID: ${GOOGLE_PROJECT_ID}
      GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI}
      SECRET_KEY: ${SECRET_KEY}
      JWT_SIGN_ALGORITHM: ${JWT_SIGN_ALGORITHM}

volumes:
  db_data:


