pipeline {
    agent any 

    stages {
        stage('Pull') {
            steps {
                echo 'Pulling the latest code from GitHub...'
                git branch: 'main', url: 'https://github.com/stefan1anuby/CRUD-app-with-google-sign-in.git'
            }
        }

        stage('Build') {
            steps {
                echo 'Building the Docker image...'
                // Build the Docker image using the Dockerfile in the repository
                sh 'docker build -t my-fastapi-app ./backend'
            }
        }

        stage('Test') {
            steps {
                echo 'Running tests...'
                
                sh '''
                docker run --rm \
                -e SECRET_KEY=$SECRET_KEY \
                -e JWT_SIGN_ALGORITHM=$JWT_SIGN_ALGORITHM \
                -e STAGE=TEST \
                my-fastapi-app pytest app/tests
                '''
                
            }
        }

        stage('Push') {
            steps {
                echo 'Pushing the build artifacts...'
                // TODO: push to ECR or something
            }
        }
    }
    
    post {
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed.'
        }
    }
}
